import type { PipelineRun } from '../types';

export const pipelineRuns: PipelineRun[] = [
  {
    id: 'clean-pass',
    label: 'Clean pass',
    gatePolicy: ['critical', 'high'],
    gateDecision: 'pass',
    stages: [
      { id: 'build', name: 'Build', status: 'pass', findingIds: [] },
      { id: 'test', name: 'Test', status: 'pass', findingIds: [] },
      { id: 'sast', name: 'SAST', status: 'pass', findingIds: [] },
      { id: 'secrets', name: 'Secrets', status: 'pass', findingIds: [] },
      { id: 'sca', name: 'SCA', status: 'pass', findingIds: [] },
      { id: 'iac', name: 'IaC', status: 'pass', findingIds: [] },
      { id: 'gate', name: 'Gate', status: 'pass', findingIds: [] },
    ],
    findings: [],
  },
  {
    id: 'blocked-sast-secrets',
    label: 'Blocked on HIGH (SAST + secrets)',
    gatePolicy: ['critical', 'high'],
    gateDecision: 'blocked',
    stages: [
      { id: 'build', name: 'Build', status: 'pass', findingIds: [] },
      { id: 'test', name: 'Test', status: 'pass', findingIds: [] },
      { id: 'sast', name: 'SAST', status: 'fail', findingIds: ['f1', 'f2', 'f3'] },
      { id: 'secrets', name: 'Secrets', status: 'fail', findingIds: ['f4'] },
      { id: 'sca', name: 'SCA', status: 'pass', findingIds: ['f5'] },
      { id: 'iac', name: 'IaC', status: 'pass', findingIds: [] },
      { id: 'gate', name: 'Gate', status: 'fail', findingIds: ['f1', 'f2', 'f4'] },
    ],
    findings: [
      {
        id: 'f1',
        scanner: 'Semgrep',
        rule: 'csharp.jwt-hardcoded-signing-key',
        severity: 'high',
        location: 'src/Auth/TokenService.cs:44',
        canonicalKey: 'hardcoded-signing-key',
      },
      {
        id: 'f2',
        scanner: 'Gitleaks',
        rule: 'generic-api-key',
        severity: 'high',
        location: 'src/Auth/TokenService.cs:44',
        canonicalKey: 'hardcoded-signing-key',
      },
      {
        id: 'f3',
        scanner: 'Bandit',
        rule: 'B608 SQL string construction',
        severity: 'medium',
        location: 'tools/importer.py:81',
        canonicalKey: 'sql-string-construction',
      },
      {
        id: 'f4',
        scanner: 'Gitleaks',
        rule: 'azure-storage-account-key',
        severity: 'critical',
        location: '.env.example:7',
        canonicalKey: 'storage-account-key',
      },
      {
        id: 'f5',
        scanner: 'OSV-Scanner',
        rule: 'GHSA sample dependency advisory',
        severity: 'low',
        location: 'package-lock.json',
        canonicalKey: 'sample-low-advisory',
      },
    ],
  },
  {
    id: 'blocked-iac',
    label: 'Blocked on IaC (Checkov)',
    gatePolicy: ['critical', 'high'],
    gateDecision: 'blocked',
    stages: [
      { id: 'build', name: 'Build', status: 'pass', findingIds: [] },
      { id: 'test', name: 'Test', status: 'pass', findingIds: [] },
      { id: 'sast', name: 'SAST', status: 'pass', findingIds: [] },
      { id: 'secrets', name: 'Secrets', status: 'pass', findingIds: [] },
      { id: 'sca', name: 'SCA', status: 'pass', findingIds: ['f6'] },
      { id: 'iac', name: 'IaC', status: 'fail', findingIds: ['f7', 'f8'] },
      { id: 'gate', name: 'Gate', status: 'fail', findingIds: ['f7'] },
    ],
    findings: [
      {
        id: 'f6',
        scanner: 'Trivy',
        rule: 'CVE sample transitive dependency',
        severity: 'medium',
        location: 'Dockerfile',
        canonicalKey: 'sample-medium-cve',
      },
      {
        id: 'f7',
        scanner: 'Checkov',
        rule: 'CKV_AZURE_33 storage container public access',
        severity: 'high',
        location: 'infra/storage.tf:19',
        canonicalKey: 'public-storage-container',
      },
      {
        id: 'f8',
        scanner: 'Checkov',
        rule: 'CKV_AZURE_35 storage account permits public blobs',
        severity: 'high',
        location: 'infra/storage.tf:4',
        canonicalKey: 'public-storage-container',
      },
    ],
  },
];
