import type { PipelineRun } from './types';

export const pipelineRuns: PipelineRun[] = [
  {
    id: 'clean-pass',
    label: 'Clean pass',
    description: 'A low-noise run where each scanner completes and the release gate passes.',
    gatePolicy: ['critical', 'high'],
    gateDecision: 'pass',
    stages: [
      { id: 'build', name: 'Build', status: 'pass', findingIds: [], logs: ['restore completed', 'unit tests passed', 'artifact signed'] },
      { id: 'sast', name: 'SAST', status: 'pass', findingIds: [], logs: ['Semgrep rules loaded', 'Bandit baseline checked', '0 blocking findings'] },
      { id: 'secrets', name: 'Secrets', status: 'pass', findingIds: [], logs: ['Gitleaks scanned 148 commits', 'no active secrets found'] },
      { id: 'sca', name: 'SCA', status: 'pass', findingIds: [], logs: ['OSV-Scanner completed', 'Trivy dependency scan clean'] },
      { id: 'container', name: 'Container', status: 'pass', findingIds: [], logs: ['image built', 'Trivy image scan completed'] },
      { id: 'iac', name: 'IaC', status: 'pass', findingIds: [], logs: ['Checkov evaluated Terraform plan', '0 high IaC findings'] },
      { id: 'gate', name: 'Gate', status: 'pass', findingIds: [], logs: ['policy: block critical/high unresolved', 'verdict: PASS'] },
    ],
    findings: [],
  },
  {
    id: 'vulnerable-run',
    label: 'Vulnerable run',
    description: 'A sample run where findings stream in, duplicates collapse, and the gate blocks with exit 3.',
    gatePolicy: ['critical', 'high'],
    gateDecision: 'blocked',
    stages: [
      { id: 'build', name: 'Build', status: 'pass', findingIds: [], logs: ['restore completed', 'unit tests passed', 'artifact ready'] },
      { id: 'sast', name: 'SAST', status: 'fail', findingIds: ['f1', 'f2', 'f3'], logs: ['Semgrep found hardcoded signing key', 'Bandit flagged SQL string construction', 'ESLint-security completed'] },
      { id: 'secrets', name: 'Secrets', status: 'fail', findingIds: ['f4', 'f5'], logs: ['Gitleaks detected Azure storage key', 'duplicate evidence matched SAST location'] },
      { id: 'sca', name: 'SCA', status: 'pass', findingIds: ['f6'], logs: ['OSV-Scanner found low advisory', 'not blocking under current policy'] },
      { id: 'container', name: 'Container', status: 'pass', findingIds: ['f7'], logs: ['Trivy found medium base image CVE', 'fix available in next patch image'] },
      { id: 'iac', name: 'IaC', status: 'fail', findingIds: ['f8', 'f9'], logs: ['Checkov found public storage container', 'Checkov found account permits public blobs'] },
      { id: 'gate', name: 'Gate', status: 'fail', findingIds: ['f1', 'f4', 'f8'], logs: ['policy: block critical/high unresolved', 'canonical groups: 4', 'verdict: BLOCKED exit 3'] },
    ],
    findings: [
      {
        id: 'f1',
        scanner: 'Semgrep',
        rule: 'csharp.jwt-hardcoded-signing-key',
        severity: 'high',
        cvss: 8.1,
        location: 'src/Auth/TokenService.cs:44',
        canonicalKey: 'hardcoded-signing-key',
        owasp: 'A02:2021 Cryptographic Failures',
        cwe: 'CWE-798',
        summary: 'Signing material appears directly in application source.',
      },
      {
        id: 'f2',
        scanner: 'Gitleaks',
        rule: 'generic-api-key',
        severity: 'high',
        cvss: 8.1,
        location: 'src/Auth/TokenService.cs:44',
        canonicalKey: 'hardcoded-signing-key',
        owasp: 'A02:2021 Cryptographic Failures',
        cwe: 'CWE-798',
        summary: 'Secret-pattern evidence points to the same canonical issue.',
      },
      {
        id: 'f3',
        scanner: 'Bandit',
        rule: 'B608 SQL string construction',
        severity: 'medium',
        cvss: 6.4,
        location: 'tools/importer.py:81',
        canonicalKey: 'sql-string-construction',
        owasp: 'A03:2021 Injection',
        cwe: 'CWE-89',
        summary: 'String-built SQL query should use parameters.',
      },
      {
        id: 'f4',
        scanner: 'Gitleaks',
        rule: 'azure-storage-account-key',
        severity: 'critical',
        cvss: 9.1,
        location: '.env.example:7',
        canonicalKey: 'storage-account-key',
        owasp: 'A07:2021 Identification and Authentication Failures',
        cwe: 'CWE-522',
        summary: 'A sample Azure storage key appears in committed configuration.',
      },
      {
        id: 'f5',
        scanner: 'Semgrep',
        rule: 'config.committed-storage-key',
        severity: 'critical',
        cvss: 9.1,
        location: '.env.example:7',
        canonicalKey: 'storage-account-key',
        owasp: 'A07:2021 Identification and Authentication Failures',
        cwe: 'CWE-522',
        summary: 'Second scanner confirms the same leaked credential pattern.',
      },
      {
        id: 'f6',
        scanner: 'OSV-Scanner',
        rule: 'GHSA sample dependency advisory',
        severity: 'low',
        cvss: 3.1,
        location: 'package-lock.json',
        canonicalKey: 'sample-low-advisory',
        owasp: 'A06:2021 Vulnerable and Outdated Components',
        cwe: 'CWE-1104',
        summary: 'Low-severity transitive advisory exists but does not block this policy.',
      },
      {
        id: 'f7',
        scanner: 'Trivy',
        rule: 'CVE sample base image advisory',
        severity: 'medium',
        cvss: 5.8,
        location: 'Dockerfile',
        canonicalKey: 'base-image-medium-cve',
        owasp: 'A06:2021 Vulnerable and Outdated Components',
        cwe: 'CWE-1104',
        summary: 'Base image should be patched during the next container refresh.',
      },
      {
        id: 'f8',
        scanner: 'Checkov',
        rule: 'CKV_AZURE_33 storage container public access',
        severity: 'high',
        cvss: 8.6,
        location: 'infra/storage.tf:19',
        canonicalKey: 'public-storage-container',
        owasp: 'A01:2021 Broken Access Control',
        cwe: 'CWE-284',
        summary: 'Blob container allows public access.',
      },
      {
        id: 'f9',
        scanner: 'Checkov',
        rule: 'CKV_AZURE_35 storage account permits public blobs',
        severity: 'high',
        cvss: 8.6,
        location: 'infra/storage.tf:4',
        canonicalKey: 'public-storage-container',
        owasp: 'A01:2021 Broken Access Control',
        cwe: 'CWE-284',
        summary: 'Storage account permits public child items.',
      },
    ],
  },
];
